name: website deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: checkout
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@master

      # 安装Node10
      - name: setup-node
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      # 安装依赖
      - name: install
        run: npm install

      # 打包
      - name: build
        run: npm run build
      # 上传阿里云
      - name: ssh deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: 'ssh scp ssh pipelines'
          LASTSSH: 'Doing something after copying'
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          pass: ${{ secrets.PRIVATE_KEY }}
          connect_timeout: 10s
          first_ssh: |
            rm -rf /opt/app/toolkit/*
          scp: |
            './dist/*' => /opt/app/toolkit/
